version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - mvn compile      
  post_build:
    commands:
      - mvn package
      - mkdir artifact  
      - unzip target/Hello.war -d artifact/
      - mv artifact/WEB-INF WEB-INF
      - mv artifact/index.jsp index.jsp
artifacts:
  files:
    - WEB-INF/**/*
    - index.jsp

        
